---
title: "Desert Springs Data Exploration"
output: html_notebook
---
```{r loadpackages}
library(RODBC)
library(tidyverse)
```

```{r functions}
selectNA <- function(data, drop.complete.cols = FALSE, cols.to.keep = NA, cols.to.ignore = NA) {
  # Given a data frame, returns only the rows that contain NA values. Optionally, omits columns that are not missing any data.
  #
  # Args:
  #   data: a data frame or tibble
  #   cols.to.ignore: a charcter vector of the names of the columns that should not be checked for missing data.
  #   drop.complete.cols: boolean value indicating whether the result should omit columns that aren't missing data.
  #   cols.to.keep: a character vector containing the names of the columns that should be returned even if drop.complete.cols is set to TRUE.
  
  # filter data to only include rows that contain one or more NA
  if (anyNA(cols.to.ignore)) {
    na.list <- data %>%
    filter_all(any_vars(is.na(.)))
  } else {
    na.list <- data %>%
    filter_at(vars(-cols.to.ignore), any_vars(is.na(.)))
  }
  
  
  # get list of columns that contain NA's
  na.cols <- na.list %>% 
    select_if(anyNA) %>%
    names()

  # if user opts to drop columns that aren't missing data, return tibble of rows and columns containing NA values, plus any additional columns specified by cols.to.keep
  if (drop.complete.cols) {
    if (anyNA(cols.to.keep)) {
      na.list <- na.list %>% 
      select(na.cols)
    } else {
      na.list <- na.list %>% 
      select(c(cols.to.keep, na.cols))
    }
  }
  
  return(na.list)
}

```

## Connecting to the database
```{r}
DS.dsn <- 'driver={SQL Server Native Client 11.0};server=INPLAKE52V\\MOJN;database=MOJN_DS_Water;trusted_connection=Yes;applicationintent=readonly'
DS.conn <- odbcDriverConnect(DS.dsn)

# Read data from analysis views in MOJN_DS_Water database

site <- sqlFetch(DS.conn, "analysis.Site", as.is = TRUE) %>% as_tibble()
visit <- sqlFetch(DS.conn, "analysis.Visit", as.is = TRUE) %>% as_tibble()
visit.activity <- sqlFetch(DS.conn, "analysis.VisitActivity", as.is = TRUE) %>% as_tibble()
wq.DO <- sqlFetch(DS.conn, "analysis.WaterQualityDO", as.is = TRUE) %>% as_tibble()
wq.pH <- sqlFetch(DS.conn, "analysis.WaterQualitypH", as.is = TRUE) %>% as_tibble()
wq.SpCond <- sqlFetch(DS.conn, "analysis.WaterQualitySpCond", as.is = TRUE) %>% as_tibble()
wq.tempC <- sqlFetch(DS.conn, "analysis.WaterQualityTemperature", as.is = TRUE) %>% as_tibble()
discharge.estimated <- sqlFetch(DS.conn, "analysis.DischargeEstimated", as.is = TRUE) %>% as_tibble()
discharge.flow <- sqlFetch(DS.conn, "analysis.DischargeFlowCondition", as.is = TRUE) %>% as_tibble()
discharge.volumetric <- sqlFetch(DS.conn, "analysis.DischargeVolumetric", as.is = TRUE) %>% as_tibble()
disturbance <- sqlFetch(DS.conn, "analysis.Disturbance", as.is = TRUE) %>% as_tibble()
disturbance.flowmod <- sqlFetch(DS.conn, "analysis.DisturbanceFlowModification", as.is = TRUE) %>% as_tibble()
invasives <- sqlFetch(DS.conn, "analysis.Invasives", as.is = TRUE) %>% as_tibble()
riparian <- sqlFetch(DS.conn, "analysis.Riparian", as.is = TRUE) %>% as_tibble()
wildlife <- sqlFetch(DS.conn, "analysis.Wildlife", as.is = TRUE) %>% as_tibble()

# Close database connection
close(DS.conn)
```

## Exploratory analysis

### Site

#### All data
```{r site}
site
```

#### Checking for NA values

```{r}
na.site <- site %>%
  selectNA()

na.site
```
There are `r nrow(na.site)` sites that are missing data. Any rows missing data are displayed above.

### Visit
```{r visit}
visit
```

#### Checking for NA values

```{r}
na.visit <- visit %>%
  selectNA(drop.complete.cols = TRUE, cols.to.keep = c("ParkCode", "SiteCode", "SiteName", "VisitDate"))
na.visit
```
There are `r nrow(na.visit)` visits that are missing data. Any rows missing data are displayed above.
